def foobar
  puts 'hello, ruby!!!!!!!!'
  puts 'hello, ruby!!!!!!!!'
  puts 'hello, ruby!!!!!!!!'
  puts 'hello, ruby!!!!!!!!'
  puts 'hello, ruby!!!!!!!!'
  puts 'hello, ruby!!!!!!!!'
  puts 'hello, ruby!!!!!!!!'
  puts 'hello, ruby!!!!!!!!'
  puts 'hello, ruby!!!!!!!!'
  puts 'hello, ruby!!!!!!!!'
  puts 'hello, ruby!!!!!!!!'
  puts 'hello, ruby!!!!!!!!'
  puts 'hello, ruby!!!!!!!!'
  puts 'hello, ruby!!!!!!!!'
  puts 'hello, ruby!!!!!!!!'
  puts 'hello, ruby!!!!!!!!'
  puts 'hello, ruby!!!!!!!!'
  puts 'hello, ruby!!!!!!!!'
end
